package cs1302.test;

import cs1302.adt.StringList;
import cs1302.oracle.OracleStringList;
import cs1302.p2.ArrayStringList;
import cs1302.p2.LinkedStringList;

/**
 * A reusable tester class for {@link cs1302.adt.StringList}
 * implementations.
 *
 * <p>
 * <strong>How to use this class:</strong>
 *
 * <p>
 * Authors of classes that implement {@link cs1302.adt.StringList}
 * should adjust the return statement inside the {@link
 * StringListTester#newStringList()} method to configure which
 * implementation class will tested.
 *
 * <p>
 * <strong>How to setup multiple tester classes:</strong>
 *
 * <p>
 * If you you want to set things up so that you can test multiple
 * implementations at once, then it's very easy to accomplish that
 * with this setup using inheritance!
 *
 * <p>
 * Suppose you want to setup separate tester classes for {@link
 * cs1302.oracle.OracleStringList} and {@link
 * cs1302.p2.ArrayStringList} so that your {@code test.sh} script can
 * run both them.
 *
 * <!--
 *   Display the stuff below as ordered list (ol) of list items (li>
 *   when viewing on the websute generated by the Javadoc tool.
 * //-->
 * <ol>
 *   <li>
 *     <p>
 *       Create a new {@code cs1302.test.OracleStringListTester} class
 *       that extends {@link cs1302.test.StringListTester}.
 *       Inside that class, override the {@link
 *       StringListTester#newStringList()} method to return {@code new
 *       OracleStringList()} and include a {@code main} similar to the
 *       one in this file (simply change {@code new
 *       StringListTester()} to {@code new OracleStringListTester()}.
 *     </p>
 *   </li>
 *   <li>
 *     <p>
 *       Next, update your scripts: i) add the command to compile the
 *       new {@code OracleStringListTester.java} file that you created
 *       to an appropriate place in {@code compile.sh}; and ii)
 *       replace the command that runs {@code
 *       cs1302.test.StringListTester} in {@code test.sh} with the
 *       command to run {@code cs1302.test.OracleStringListTester}
 *       instead.
 *     </p>
 *   </li>
 *   <li>
 *     <p>
 *       Repeat and adjust, as needed, the process you just followed
 *       to create a new {@code cs1302.test.ArrayStringListTester}
 *       class and update your {@code compile.sh} script. When you
 *       update your {@code test.sh} script, add the command to run
 *       {@code cs1302.test.ArrayStringListTester} immediately after
 *       the command that runs {@code
 *       cs1302.test.OracleStringListTester}.
 *     </p>
 *   </li>
 * </ol>
 *
 * <p>
 * <em>Why stop at two?</em> You are encouraged to also create a
 * {@code cs1302.test.LinkedStringListTester} class and adjust your
 * scripts so that you're always testing all three implementations
 * when running {@code test.sh}.
 *
 * <p>
 * Doing this will enable you to easily confirm that your tests
 * methods pass when testing a {@link cs1302.oracle.OracleStringList}
 * object before observing whether those same tests pass or fail when
 * testing one of your own implementations.
 */
public class StringListTester {

    /**
     * Construct a new {@link cs1302.test.StringListTester} object.
     */
    public StringListTester() {
        super();
        System.out.printf("[%s Tester]\n", this.newStringList().getClass().getName());
    } // StringListTester

    /**
     * Return a new, empty {@link cs1302.adt.StringList} object.
     *
     * @return A reference to a new, empty string list object.
     * @throws UnsupportedOperationException If the method has not been configured
     *     to return with a reference to some object yet.
     */
    public StringList newStringList() {
        /*
         * UNCOMMENT A LINE BELOW TO TEST A CLASS OR INDICATE THAT THE TESTER IS NOT SETUP.
         */
        throw new UnsupportedOperationException("newStringList() not yet configured");
        // return new OracleStringList();
        // return new ArrayStringList();
        // return new LinkedStringList();
    } // newStringList

    // ------------------------------------------------------------------------------------------ //
    // BEGIN TEST METHODS
    // ------------------------------------------------------------------------------------------ //

    /**
     * Test Scenario 1.
     *
     * No exceptions are expected to be thrown when you construct a
     * new, empty string list object using the the class's default
     * constructor (via {@link #newStringList()}).
     *
     * @throws AssertionError If the test fails.
     */
    public void testScenario1() {
        try {
            StringList list = this.newStringList();
        } catch (Throwable cause) {
            throw new AssertionError(
                "Unexpected exception thrown!",
                cause // let's this exception know about the unexpected exception that was caught
            );
        } // try
    } // testScenario1

    /**
     * Test Scenario 2.
     *
     * The {@link StringList#size()} of a new string list object is expected to be {@code 0}.
     *
     * @throws AssertionError If the test fails.
     */
    public void testScenario2() {

        StringList list = this.newStringList();

        int expected = 0;
        int actual = list.size();

        if (actual != expected) {
            String message = String.format("size(): expected = %d; actual = %d", expected, actual);
            throw new AssertionError(message);
        } // if

    } // testScenario2

    /**
     * Test Scenario 3.
     *
     * A new, empty string list should report itself as empty when
     * calling {@link StringList#isEmpty()}.
     *
     * @throws AssertionError If the test fails.
     */
    public void testScenario3() {

        StringList list = this.newStringList();

        boolean expected = true;
        boolean actual = list.isEmpty();

        if (actual != expected) {
            String message = String.format(
                "isEmpty(): expected = %s; actual = %s",
                expected, actual
            );
            throw new AssertionError(message);
        } // if

    } // testScenario3

    /**
     * Test Scenario 4.
     *
     * Replace this sentence with your own description of the test.
     *
     * @throws AssertionError If the test fails.
     */
    public void testScenario4() {
        //
        // StringList list = this.newStringList();
        // list.add(0, "a");
        //
        throw new UnsupportedOperationException("test method not yet implemented!");
    } // testScenario4

    /**
     * Test Scenario 5.
     *
     * Replace this sentence with your own description of the test.
     *
     * @throws AssertionError If the test fails.
     */
    public void testScenario5() {
        //
        // StringList list = this.newStringList();
        // list.add(0, "a");
        //
        throw new UnsupportedOperationException("test method not yet implemented!");
    } // testScenario5

    // ------------------------------------------------------------------------------------------ //
    // END TEST METHODS - do NOT forget to add calls to new test methods in testAll() below.
    // ------------------------------------------------------------------------------------------ //

    /**
     * Run all the tests.
     *
     * <p>
     * If {@code testAll()} gets too long, then you should group
     * and move calls to related test methods into a separate new
     * method for that group (e.g., something like {@code
     * testScenarioGroup1()}), then call that method here instead.
     *
     * @throws AssertionError If a test fails.
     */
    public void testAll() {
        // run the starter code tests
        this.testScenario1();
        this.testScenario2();
        this.testScenario3();
        // run your additional tests
        this.testScenario4();
        this.testScenario5();
    } // testAll

    // ------------------------------------------------------------------------------------------ //
    // MAIN METHOD - should not need to be updated often, if at all.
    // ------------------------------------------------------------------------------------------ //

    /**
     * The main entry-point into the {@link StringListTester} program.
     *
     * @param args The command-line arguments (not used).
     * @throws AssertionError If a test fails.
     */
    public static void main(String[] args) {
        StringListTester tester = new StringListTester();
        tester.testAll();
    } // main

    // ------------------------------------------------------------------------------------------ //

} // StringListTester
